version: '2'
services: 

  laravel:
    image: simple-nginx
    networks:
      project-2:
        aliases:
          - laravel
    command: "bash-tail"
    volumes:
      - ./laravel/etc/nginx:/etc/nginx:ro
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"

  laravel-php-fpm:
    image: simple-php-fpm
    networks:
      project-2:
        aliases:
          - laravel-php-fpm
    command: "bash-tail"
    volumes:
      - ./laravel/etc/php5:/etc/php5:ro
      - ./laravel/install-laravel.sh:/install-laravel.sh
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"

  adminer:
    image: simple-nginx
    networks:
      project-2:
        aliases:
          - adminer
    command: "bash-tail"
    volumes:
      - ./adminer/etc/nginx:/etc/nginx:ro
      - ./adminer/var/www:/var/www
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"

  adminer-php-fpm:
    image: simple-php-fpm
    networks:
      project-2:
        aliases:
          - adminer-php-fpm
    command: "bash-tail"
    volumes:
      - ./adminer/etc/php5:/etc/php5:ro
      - ./adminer/var/www:/var/www
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"

networks:
  project-2:
    driver: "bridge"


volumes:
  site: