version: '2'
services:
  
  kibana: 
    image: kibana:5.0.0-rc1
    networks:
      monitoring:
        aliases:
          - kibana
    ports: 
      - ${KIBANA_UI}:5601
    volumes:
      - ./etc/kibana/kibana.yml:/etc/kibana/kibana.yml:ro
    depends_on: 
      - elasticsearch
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"

  elasticsearch: 
    image: elasticsearch:5.0.0-rc1
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks: 
      monitoring:
        aliases:
          - elasticsearch
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"

  logstash:
    image: logstash:5.0.0-rc1-1
    networks:
      monitoring:
        aliases:
          - logstash
    depends_on: 
      - elasticsearch
    volumes: 
      - ./logstash/config-dir:/config-dir:ro
    command: -f /config-dir/logstash.conf --config.reload.automatic
    ports:
      - ${LOGSTASH_INPUT_HTTP}:3002 # http
      - ${LOGSTASH_INPUT_TCP}:3001 # tcp
      - ${LOGSTASH_INPUT_UDP}:3000 # udp
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"

networks:
  monitoring:
    driver: "bridge"